name: Generate Atom Feed and Publish to GitHub Pages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'  # Runs at 06:00 AM every Monday

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Run Go script
      run: go run main.go > ./build/feed

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        build_dir: ./  # The directory where atom.xml is generated
        pages_token: ${{ secrets.GITHUB_TOKEN }}

